---
- hosts: test
  gather_facts: False
  remote_user: root
  become_method: sudo 
  
  tasks:
    - name: tomcat stop
      service: 
        name: tomcat
        state: stopped

    - name: delete old war
      file: 
        path: /opt/tomcat/webapps/*
        state: absent
        
    - name: copying war file
      copy: 
        src: /var/lib/jenkins/workspace/java-Build/target/vprofile-v1.war
        dest: /opt/tomcat/webapps
        
    - name: tomcat start
      service: 
        name: tomcat
        state: started
